name: Deploy Peerplay Update
on:
  workflow_dispatch:
    inputs:
      peerplay_version:
        description: 'Peerplay General version'
        required: true
        default: ''
        type: string
      lan_play_version:
        description: 'Lan Play Client Release version'
        required: true
        default: '0.2.3'
        type: string
      pre_release:
        description: 'Is this version is a pre-release'
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: |
          npm install
          mkdir artifacts
      - name: Download Peerplay CR Client Artifact
        run: |
          cd artifacts
          curl -sLJO "https://nightly.link/peerplay-project/peerplay_CR_client/workflows/build/master-peerplay/peerplay-cr-client-build.zip"
          cd ..
      - name: Download Peerplay CR Server Artifact
        run: |
          cd artifacts
          curl -sLJO "https://nightly.link/peerplay-project/peerplay_CR_server/workflows/build/master-peerplay/peerplay-cr-server-build.zip"
          cd ..
      - name: Extract Peerplay CR Client (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir peerplay_CR_client
          unzip artifacts/peerplay-cr-client-build -d peerplay_CR_client
          cp -r peerplay_CR_client/software resources/peerplay_tools/cr_client
          Remove-Item -Recurse -Force resources/peerplay_tools/cr_client/software/linux
          Remove-Item -Recurse -Force resources/peerplay_tools/cr_client/software/macos
      - name: Extract Peerplay CR Client (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir peerplay_CR_client
          unzip artifacts/peerplay-cr-client-build -d peerplay_CR_client
          cp -r peerplay_CR_client/software resources/peerplay_tools/cr_client
          rm -rf resources/peerplay_tools/cr_client/software/windows
          rm -rf resources/peerplay_tools/cr_client/software/linux
      - name: Extract Peerplay CR Client (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir peerplay_CR_client
          unzip artifacts/peerplay-cr-client-build -d peerplay_CR_client
          cp -r peerplay_CR_client/software resources/peerplay_tools/cr_client
          rm -rf resources/peerplay_tools/cr_client/software/windows
          rm -rf resources/peerplay_tools/cr_client/software/macos
      - name: Extract Peerplay CR Server
        run: |
          mkdir peerplay_CR_server
          cd peerplay_CR_server
          mkdir software
          cd ..
          unzip artifacts/peerplay-cr-server-build -d peerplay_CR_server
          cp -r peerplay_CR_server resources/peerplay_tools/cr_server/software
          
      - name: Download Latest Switch Lan play Release (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir resources/peerplay_tools/lan_play/software
          mkdir resources/peerplay_tools/lan_play/software/windows
          curl -sL -o resources/peerplay_tools/lan_play/software/windows/lan-play.exe https://github.com/spacemeowx2/switch-lan-play/releases/latest/download/lan-play-win64.exe
      - name: Download Latest Switch Lan play Releases (Mac OS)
        if: matrix.os == 'macos-latest'
        run: |
          mkdir resources/peerplay_tools/lan_play/software
          mkdir resources/peerplay_tools/lan_play/software/macos
          curl -sL -o resources/peerplay_tools/lan_play/software/macos/lan-play https://github.com/spacemeowx2/switch-lan-play/releases/latest/download/lan-play-macos
      - name: Download Latest Switch Lan play Releases (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir resources/peerplay_tools/lan_play/software
          mkdir resources/peerplay_tools/lan_play/software/linux
          curl -sL -o resources/peerplay_tools/lan_play/software/linux/lan-play https://github.com/spacemeowx2/switch-lan-play/releases/latest/download/lan-play-linux

      - name: Adapt version related files (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          (Get-Content -Path "resources/peerplay_tools/peerplay/tool.js") | ForEach-Object { $_ -replace "export const peerplay_version = 'N/A'", "export const peerplay_version = '${{ inputs.peerplay_version }}'" } | Set-Content -Path "resources/peerplay_tools/peerplay/tool.js"
          (Get-Content -Path "resources/peerplay_tools/lan_play/tool.js") | ForEach-Object { $_ -replace "export const lan_play_version = 'N/A'", "export const lan_play_version = '${{ inputs.lan_play_version  }}'" } | Set-Content -Path "resources/peerplay_tools/lan_play/tool.js"
          (Get-Content -Path "package.json") | ForEach-Object { $_ -replace "0.0.0", "${{ inputs.peerplay_version }}" } | Set-Content -Path "package.json"
      - name: Adapt version related files (Mac OS)
        if: matrix.os == 'macos-latest'
        run: |
          sed -i '' "s/export const peerplay_version = 'N\/A'/export const peerplay_version = '${{ inputs.peerplay_version }}'/g" resources/peerplay_tools/peerplay/tool.js
          sed -i '' "s/export const lan_play_version = 'N\/A'/export const lan_play_version = '${{ inputs.lan_play_version }}'/g" resources/peerplay_tools/lan_play/tool.js
          sed -i '' "s#0.0.0#${{ inputs.peerplay_version }}#g" package.json

      - name: Adapt version related files (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sed -i "s/export const peerplay_version = 'N\/A'/export const peerplay_version = '${{ inputs.peerplay_version }}'/g" resources/peerplay_tools/peerplay/tool.js
          sed -i "s/export const lan_play_version = 'N\/A'/export const lan_play_version = '${{ inputs.lan_play_version }}'/g" resources/peerplay_tools/lan_play/tool.js
          sed -i "s#0.0.0#${{ inputs.peerplay_version }}#g" package.json
      - name: Build application
        run: npm run build

      ## Archive Application
      - name: Find artifact file (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          $default_file = Get-ChildItem -Path dist -Filter "*.exe" -File | Select-Object -First 1
          $new_file_name = "Peerplay_Setup-Windows.exe"
          $new_file_path = Join-Path -Path $default_file.Directory.FullName -ChildPath $new_file_name
          Rename-Item -Path $default_file.FullName -NewName $new_file_name
          echo "windows_artifact_file=$new_file_path" >> $env:GITHUB_ENV
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-latest'
        with:
          name: Peerplay_Setup-Windows
          path: ${{ env.windows_artifact_file }}
          if-no-files-found: error
      # Mac OS
      - name: Find artifact file (MacOS)
        if: matrix.os == 'macos-latest'
        run: |
            default_file=$(find dist -name '*.dmg' -type f | head -n 1)
            mv $default_file Peerplay_Setup-MacOS.dmg
            echo "macos_artifact_file=Peerplay_Setup-MacOS.dmg" >> "$GITHUB_ENV"
      - name: Upload artifact (Mac OS)
        uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
            name: Peerplay_Setup-MacOS
            path: ${{ env.macos_artifact_file }}
            if-no-files-found: error
      # Linux
      - name: Find artifact file (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
            default_file=$(find dist -name '*.AppImage' -type f | head -n 1)
            mv $default_file Peerplay_Setup-Linux.AppImage
            echo "linux_artifact_file=Peerplay_Setup-Linux.AppImage" >> "$GITHUB_ENV"
      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
            name: Peerplay_Setup-Linux
            path: ${{ env.linux_artifact_file }}
            if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        platform: [Linux, Windows, MacOS]
    steps:
      - name: Create download directory
        run: mkdir peerplay_setups
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: Peerplay_Setup-${{ matrix.platform }}
          path: peerplay_setups/
      - name: Create Release
        id: create
        uses: softprops/action-gh-release@v1
        with:
          prerelease: ${{ inputs.pre_release }}
          tag_name: ${{ inputs.peerplay_version }}
          files: |
            peerplay_setups/Peerplay_Setup-Windows.exe
            peerplay_setups/Peerplay_Setup-Linux.AppImage
            peerplay_setups/Peerplay_Setup-MacOS.dmg
        env:
          GITHUB_TOKEN: ${{ github.token }}